
- name: ls Sample
  hosts: Static resource server
  remote_user: test
  tasks:
  - name: just ls
    shell: ls /
    register: result
  
  - name: get ls
    debug: 
      msg: "{{ result.stdout }}"
 
